version: "3.1"

services:
  database:
    image: postgres:latest
    environment:
      - "POSTGRES_USER=testePratico"
      - "POSTGRES_PASSWORD=dev123456"
      - "POSTGRES_DB=manager"
    ports:
      - 5441:5432
    volumes:
      - pg-data:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "3000:3000"
volumes:
  pg-data: