// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/Lucas-Linhar3s/Teste-Pratico-Flutter-Golang/backend/database"
	"github.com/Lucas-Linhar3s/Teste-Pratico-Flutter-Golang/backend/modules/courses"
	"github.com/Lucas-Linhar3s/Teste-Pratico-Flutter-Golang/backend/modules/courses/application"
	"github.com/Lucas-Linhar3s/Teste-Pratico-Flutter-Golang/backend/modules/courses/interfaces"
	"github.com/Lucas-Linhar3s/Teste-Pratico-Flutter-Golang/backend/modules/students"
	application2 "github.com/Lucas-Linhar3s/Teste-Pratico-Flutter-Golang/backend/modules/students/application"
	interfaces2 "github.com/Lucas-Linhar3s/Teste-Pratico-Flutter-Golang/backend/modules/students/interfaces"
	"github.com/Lucas-Linhar3s/Teste-Pratico-Flutter-Golang/backend/pkg/config"
	"github.com/Lucas-Linhar3s/Teste-Pratico-Flutter-Golang/backend/pkg/http/server"
	"github.com/Lucas-Linhar3s/Teste-Pratico-Flutter-Golang/backend/pkg/jwt"
	"github.com/Lucas-Linhar3s/Teste-Pratico-Flutter-Golang/backend/pkg/log"
	"github.com/google/wire"
)

// Injectors from wire.go:

func Initialize() (*App, func(), error) {
	serverServer := server.NewServer()
	viper := config.NewViper()
	configConfig := config.LoadAttributes(viper)
	logger := log.NewLog(configConfig)
	databaseDatabase := database.NewDatabase(configConfig, logger)
	courseApp := application.NewApplication(logger, databaseDatabase)
	courseHandler := interfaces.NewHander(courseApp)
	module := courses.ModuleRegister(logger, serverServer, courseHandler)
	studentApp := application2.NewApplication(logger, databaseDatabase)
	studentHandler := interfaces2.NewHander(studentApp)
	studentsModule := students.ModuleRegister(logger, serverServer, studentHandler)
	app := newApp(serverServer, configConfig, logger, module, studentsModule)
	return app, func() {
	}, nil
}

// wire.go:

type App struct {
	Server *server.Server
	Config *config.Config
	Logger *log.Logger
}

func newApp(server2 *server.Server, config2 *config.Config, logger *log.Logger,

	courseModule *courses.Module,
	studentModule *students.Module,
) *App {
	return &App{
		Server: server2,
		Config: config2,
		Logger: logger,
	}
}

var globalSet = wire.NewSet(config.NewViper, config.LoadAttributes, jwt.NewJwt, log.NewLog, server.NewServer, database.NewDatabase, newApp)
